import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { gsap } from "gsap";
// import { MotionPathPlugin } from "gsap/MotionPathPlugin";
// gsap.registerPlugin(MotionPathPlugin);
// import anime from 'animejs/lib/anime.es.js';
export default function Home() {
  let ref = React.useRef();
  React.useEffect(() => {
    ref.current;
    console.log(ref.current);
    anime({
      targets: 'div',
      translateX: 250,
      rotate: '1turn',
      backgroundColor: '#FFF',
      duration: 800
    });
    // console.log(anime())
  }, []);
  // React.useEffect(() => {
  //   gsap.to(ref.current, {
  //     // duration: 5,
  //     // repeat: 12,
  //     // repeatDelay: 3,
  //     // yoyo: true,
  //     // ease: "power1.inOut",
  //     motionPath: {
  //       path: "#path",
  //       align: "#path",
  //       autoRotate: true,
  //        alignOrigin: [0.5, 0.5],
  //     },
  //   });
  // }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="anime.min.js"></script>
      </Head>

      <main className={styles.main}>
        <svg
          width="473"
          height="88"
          viewBox="0 0 473 88"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            stroke="black"
            stroke-width="4"
            fill="white"
            className={styles.path}
            d="M8.40625 79H41.2699C56.4403 79 65.8153 70.7159 65.8153 59.2273C65.8153 49.375 58.554 42.9318 49.5881 42.5909V41.9091C57.6676 40.3068 63.0881 34.3409 63.0881 26.6364C63.0881 16 54.6335 9.18182 38.679 9.18182H8.40625V79ZM27.3608 63.8636V49.1364H36.4972C42.2585 49.1364 45.7699 51.8636 45.7699 56.7727C45.7699 61.4432 42.5994 63.8636 36.2244 63.8636H27.3608ZM27.3608 37.4091V24.0455H35.4062C40.1108 24.0455 43.5881 26.4318 43.5881 30.7273C43.5881 35.0227 40.1108 37.4091 35.1335 37.4091H27.3608ZM90.6676 79L94.6903 65.6364H117.736L121.759 79H142.213L119.168 9.18182H93.2585L70.2131 79H90.6676ZM98.9858 51.4545L105.94 28.4091H106.486L113.44 51.4545H98.9858ZM209.347 9.18182H190.392V45.7273H189.847L165.028 9.18182H148.938V79H167.892V42.3182H168.301L193.528 79H209.347V9.18182ZM218.312 79H237.267V61L243.54 52.8182L259.222 79H281.858L257.722 40.2727L281.312 9.18182H259.222L238.222 37.4091H237.267V9.18182H218.312V79ZM350.168 44.0909C350.168 20.7727 335.168 8.22727 316.213 8.22727C297.122 8.22727 282.259 20.7727 282.259 44.0909C282.259 67.2727 297.122 79.9545 316.213 79.9545C335.168 79.9545 350.168 67.4091 350.168 44.0909ZM330.668 44.0909C330.668 56.6364 325.622 63.4545 316.213 63.4545C306.804 63.4545 301.759 56.6364 301.759 44.0909C301.759 31.5455 306.804 24.7273 316.213 24.7273C325.622 24.7273 330.668 31.5455 330.668 44.0909ZM358.938 79H406.119V63.7273H377.892V9.18182H358.938V79ZM413.781 79H463.963V63.7273H432.736V51.7273H461.509V36.4545H432.736V24.4545H464.099V9.18182H413.781V79Z"
          />
        </svg>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
